/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GsiApi.Client;
using GsiApi.Api;
// uncomment below to import models
//using GsiApi.Model;

namespace GsiApi.Test.Api
{
    /// <summary>
    ///  Class for testing GeoidApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GeoidApiTests : IDisposable
    {
        private GeoidApi instance;

        public GeoidApiTests()
        {
            instance = new GeoidApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeoidApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GeoidApi
            //Assert.IsType<GeoidApi>(instance);
        }

        /// <summary>
        /// Test GeoidCalcghCgiGeoidcalcPlGet
        /// </summary>
        [Fact]
        public void GeoidCalcghCgiGeoidcalcPlGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string outputType = null;
            //double latitude = null;
            //double longitude = null;
            //var response = instance.GeoidCalcghCgiGeoidcalcPlGet(outputType, latitude, longitude);
            //Assert.IsType<GeoidCalcghCgiGeoidcalcPlGet200Response>(response);
        }
    }
}
