/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GsiApi.Client;
using GsiApi.Api;
// uncomment below to import models
//using GsiApi.Model;

namespace GsiApi.Test.Api
{
    /// <summary>
    ///  Class for testing GravityApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GravityApiTests : IDisposable
    {
        private GravityApi instance;

        public GravityApiTests()
        {
            instance = new GravityApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GravityApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GravityApi
            //Assert.IsType<GravityApi>(instance);
        }

        /// <summary>
        /// Test GsigraCalcApiGravityCalculationGet
        /// </summary>
        [Fact]
        public void GsigraCalcApiGravityCalculationGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string unit = null;
            //double lat = null;
            //double lon = null;
            //float dH = null;
            //var response = instance.GsigraCalcApiGravityCalculationGet(unit, lat, lon, dH);
            //Assert.IsType<GsigraCalcApiGravityCalculationGet200Response>(response);
        }
    }
}
