/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GsiApi.Client;
using GsiApi.Api;
// uncomment below to import models
//using GsiApi.Model;

namespace GsiApi.Test.Api
{
    /// <summary>
    ///  Class for testing SemidynaApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SemidynaApiTests : IDisposable
    {
        private SemidynaApi instance;

        public SemidynaApiTests()
        {
            instance = new SemidynaApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SemidynaApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SemidynaApi
            //Assert.IsType<SemidynaApi>(instance);
        }

        /// <summary>
        /// Test SemidynaWebSemidynaRPhpGet
        /// </summary>
        [Fact]
        public void SemidynaWebSemidynaRPhpGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string outputType = null;
            //string chiiki = null;
            //int sokuchi = null;
            //int place = null;
            //int hoseiJ = null;
            //double latitude = null;
            //double longitude = null;
            //float? altitude1 = null;
            //int? zone = null;
            //double? publicX = null;
            //double? publicY = null;
            //float? altitude2 = null;
            //var response = instance.SemidynaWebSemidynaRPhpGet(outputType, chiiki, sokuchi, place, hoseiJ, latitude, longitude, altitude1, zone, publicX, publicY, altitude2);
            //Assert.IsType<Object>(response);
        }
    }
}
