/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GsiApi.Client;
using GsiApi.Api;
// uncomment below to import models
//using GsiApi.Model;

namespace GsiApi.Test.Api
{
    /// <summary>
    ///  Class for testing Tky2jgdApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class Tky2jgdApiTests : IDisposable
    {
        private Tky2jgdApi instance;

        public Tky2jgdApiTests()
        {
            instance = new Tky2jgdApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Tky2jgdApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' Tky2jgdApi
            //Assert.IsType<Tky2jgdApi>(instance);
        }

        /// <summary>
        /// Test Tky2jgdTky2jgdPlGet
        /// </summary>
        [Fact]
        public void Tky2jgdTky2jgdPlGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string outputType = null;
            //int sokuti = null;
            //int place = null;
            //double latitude = null;
            //double longitude = null;
            //int? zone = null;
            //double? publicX = null;
            //double? publicY = null;
            //var response = instance.Tky2jgdTky2jgdPlGet(outputType, sokuti, place, latitude, longitude, zone, publicX, publicY);
            //Assert.IsType<Object>(response);
        }
    }
}
