/*
 * 国土地理院標高API
 *
 * 指定した緯度経度の位置の標高値を取得するAPIです。 2013年3月14日より試験公開されています。  ## リクエストレート制限 サーバに過度の負担を与えないでください。過度の負担を与えると判断したアクセスについて、 国土地理院は予告なく遮断を行う場合があります。具体的な制限値は公開されていませんが、 アプリケーションの設計時には適切なレート制限を実装することを強く推奨します。 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GsiElevationApi.Client;
using GsiElevationApi.Api;
// uncomment below to import models
//using GsiElevationApi.Model;

namespace GsiElevationApi.Test.Api
{
    /// <summary>
    ///  Class for testing ElevationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ElevationApiTests : IDisposable
    {
        private ElevationApi instance;

        public ElevationApiTests()
        {
            instance = new ElevationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ElevationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ElevationApi
            //Assert.IsType<ElevationApi>(instance);
        }

        /// <summary>
        /// Test GetelevationPhpGet
        /// </summary>
        [Fact]
        public void GetelevationPhpGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //double lon = null;
            //double lat = null;
            //string outtype = null;
            //var response = instance.GetelevationPhpGet(lon, lat, outtype);
            //Assert.IsType<GetelevationPhpGet200Response>(response);
        }
    }
}
