/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using GsiApi.Client;
using GsiApi.Model;

namespace GsiApi.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITky2jgdApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 世界測地系座標変換（TKY2JGD）
        /// </summary>
        /// <exception cref="GsiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="outputType"></param>
        /// <param name="sokuti"></param>
        /// <param name="place"></param>
        /// <param name="latitude"></param>
        /// <param name="longitude"></param>
        /// <param name="zone"> (optional)</param>
        /// <param name="publicX"> (optional)</param>
        /// <param name="publicY"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        Object Tky2jgdTky2jgdPlGet(string outputType, int sokuti, int place, double latitude, double longitude, int? zone = default(int?), double? publicX = default(double?), double? publicY = default(double?), int operationIndex = 0);

        /// <summary>
        /// 世界測地系座標変換（TKY2JGD）
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GsiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="outputType"></param>
        /// <param name="sokuti"></param>
        /// <param name="place"></param>
        /// <param name="latitude"></param>
        /// <param name="longitude"></param>
        /// <param name="zone"> (optional)</param>
        /// <param name="publicX"> (optional)</param>
        /// <param name="publicY"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> Tky2jgdTky2jgdPlGetWithHttpInfo(string outputType, int sokuti, int place, double latitude, double longitude, int? zone = default(int?), double? publicX = default(double?), double? publicY = default(double?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITky2jgdApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 世界測地系座標変換（TKY2JGD）
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GsiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="outputType"></param>
        /// <param name="sokuti"></param>
        /// <param name="place"></param>
        /// <param name="latitude"></param>
        /// <param name="longitude"></param>
        /// <param name="zone"> (optional)</param>
        /// <param name="publicX"> (optional)</param>
        /// <param name="publicY"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> Tky2jgdTky2jgdPlGetAsync(string outputType, int sokuti, int place, double latitude, double longitude, int? zone = default(int?), double? publicX = default(double?), double? publicY = default(double?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 世界測地系座標変換（TKY2JGD）
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GsiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="outputType"></param>
        /// <param name="sokuti"></param>
        /// <param name="place"></param>
        /// <param name="latitude"></param>
        /// <param name="longitude"></param>
        /// <param name="zone"> (optional)</param>
        /// <param name="publicX"> (optional)</param>
        /// <param name="publicY"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> Tky2jgdTky2jgdPlGetWithHttpInfoAsync(string outputType, int sokuti, int place, double latitude, double longitude, int? zone = default(int?), double? publicX = default(double?), double? publicY = default(double?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITky2jgdApi : ITky2jgdApiSync, ITky2jgdApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class Tky2jgdApi : ITky2jgdApi
    {
        private GsiApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="Tky2jgdApi"/> class.
        /// </summary>
        /// <returns></returns>
        public Tky2jgdApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Tky2jgdApi"/> class.
        /// </summary>
        /// <returns></returns>
        public Tky2jgdApi(string basePath)
        {
            this.Configuration = GsiApi.Client.Configuration.MergeConfigurations(
                GsiApi.Client.GlobalConfiguration.Instance,
                new GsiApi.Client.Configuration { BasePath = basePath }
            );
            this.Client = new GsiApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GsiApi.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = GsiApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Tky2jgdApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public Tky2jgdApi(GsiApi.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = GsiApi.Client.Configuration.MergeConfigurations(
                GsiApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new GsiApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GsiApi.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = GsiApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Tky2jgdApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public Tky2jgdApi(GsiApi.Client.ISynchronousClient client, GsiApi.Client.IAsynchronousClient asyncClient, GsiApi.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = GsiApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public GsiApi.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public GsiApi.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public GsiApi.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public GsiApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// 世界測地系座標変換（TKY2JGD） 
        /// </summary>
        /// <exception cref="GsiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="outputType"></param>
        /// <param name="sokuti"></param>
        /// <param name="place"></param>
        /// <param name="latitude"></param>
        /// <param name="longitude"></param>
        /// <param name="zone"> (optional)</param>
        /// <param name="publicX"> (optional)</param>
        /// <param name="publicY"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        public Object Tky2jgdTky2jgdPlGet(string outputType, int sokuti, int place, double latitude, double longitude, int? zone = default(int?), double? publicX = default(double?), double? publicY = default(double?), int operationIndex = 0)
        {
            GsiApi.Client.ApiResponse<Object> localVarResponse = Tky2jgdTky2jgdPlGetWithHttpInfo(outputType, sokuti, place, latitude, longitude, zone, publicX, publicY);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 世界測地系座標変換（TKY2JGD） 
        /// </summary>
        /// <exception cref="GsiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="outputType"></param>
        /// <param name="sokuti"></param>
        /// <param name="place"></param>
        /// <param name="latitude"></param>
        /// <param name="longitude"></param>
        /// <param name="zone"> (optional)</param>
        /// <param name="publicX"> (optional)</param>
        /// <param name="publicY"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        public GsiApi.Client.ApiResponse<Object> Tky2jgdTky2jgdPlGetWithHttpInfo(string outputType, int sokuti, int place, double latitude, double longitude, int? zone = default(int?), double? publicX = default(double?), double? publicY = default(double?), int operationIndex = 0)
        {
            // verify the required parameter 'outputType' is set
            if (outputType == null)
            {
                throw new GsiApi.Client.ApiException(400, "Missing required parameter 'outputType' when calling Tky2jgdApi->Tky2jgdTky2jgdPlGet");
            }

            GsiApi.Client.RequestOptions localVarRequestOptions = new GsiApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/xml",
                "application/json"
            };

            var localVarContentType = GsiApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GsiApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "outputType", outputType));
            localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "sokuti", sokuti));
            localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "Place", place));
            localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "latitude", latitude));
            localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "longitude", longitude));
            if (zone != null)
            {
                localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "zone", zone));
            }
            if (publicX != null)
            {
                localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "publicX", publicX));
            }
            if (publicY != null)
            {
                localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "publicY", publicY));
            }

            localVarRequestOptions.Operation = "Tky2jgdApi.Tky2jgdTky2jgdPlGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/tky2jgd/tky2jgd.pl", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Tky2jgdTky2jgdPlGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// 世界測地系座標変換（TKY2JGD） 
        /// </summary>
        /// <exception cref="GsiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="outputType"></param>
        /// <param name="sokuti"></param>
        /// <param name="place"></param>
        /// <param name="latitude"></param>
        /// <param name="longitude"></param>
        /// <param name="zone"> (optional)</param>
        /// <param name="publicX"> (optional)</param>
        /// <param name="publicY"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> Tky2jgdTky2jgdPlGetAsync(string outputType, int sokuti, int place, double latitude, double longitude, int? zone = default(int?), double? publicX = default(double?), double? publicY = default(double?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            GsiApi.Client.ApiResponse<Object> localVarResponse = await Tky2jgdTky2jgdPlGetWithHttpInfoAsync(outputType, sokuti, place, latitude, longitude, zone, publicX, publicY, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 世界測地系座標変換（TKY2JGD） 
        /// </summary>
        /// <exception cref="GsiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="outputType"></param>
        /// <param name="sokuti"></param>
        /// <param name="place"></param>
        /// <param name="latitude"></param>
        /// <param name="longitude"></param>
        /// <param name="zone"> (optional)</param>
        /// <param name="publicX"> (optional)</param>
        /// <param name="publicY"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<GsiApi.Client.ApiResponse<Object>> Tky2jgdTky2jgdPlGetWithHttpInfoAsync(string outputType, int sokuti, int place, double latitude, double longitude, int? zone = default(int?), double? publicX = default(double?), double? publicY = default(double?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'outputType' is set
            if (outputType == null)
            {
                throw new GsiApi.Client.ApiException(400, "Missing required parameter 'outputType' when calling Tky2jgdApi->Tky2jgdTky2jgdPlGet");
            }


            GsiApi.Client.RequestOptions localVarRequestOptions = new GsiApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/xml",
                "application/json"
            };

            var localVarContentType = GsiApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GsiApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "outputType", outputType));
            localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "sokuti", sokuti));
            localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "Place", place));
            localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "latitude", latitude));
            localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "longitude", longitude));
            if (zone != null)
            {
                localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "zone", zone));
            }
            if (publicX != null)
            {
                localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "publicX", publicX));
            }
            if (publicY != null)
            {
                localVarRequestOptions.QueryParameters.Add(GsiApi.Client.ClientUtils.ParameterToMultiMap("", "publicY", publicY));
            }

            localVarRequestOptions.Operation = "Tky2jgdApi.Tky2jgdTky2jgdPlGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/tky2jgd/tky2jgd.pl", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Tky2jgdTky2jgdPlGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
