/*
 * 国土地理院標高API
 *
 * 指定した緯度経度の位置の標高値を取得するAPIです。 2013年3月14日より試験公開されています。  ## リクエストレート制限 サーバに過度の負担を与えないでください。過度の負担を与えると判断したアクセスについて、 国土地理院は予告なく遮断を行う場合があります。具体的な制限値は公開されていませんが、 アプリケーションの設計時には適切なレート制限を実装することを強く推奨します。 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GsiElevationApi.Model;
using GsiElevationApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GsiElevationApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetelevationPhpGet200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetelevationPhpGet200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetelevationPhpGet200Response
        //private GetelevationPhpGet200Response instance;

        public GetelevationPhpGet200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetelevationPhpGet200Response
            //instance = new GetelevationPhpGet200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetelevationPhpGet200Response
        /// </summary>
        [Fact]
        public void GetelevationPhpGet200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetelevationPhpGet200Response
            //Assert.IsType<GetelevationPhpGet200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Elevation'
        /// </summary>
        [Fact]
        public void ElevationTest()
        {
            // TODO unit test for the property 'Elevation'
        }

        /// <summary>
        /// Test the property 'Hsrc'
        /// </summary>
        [Fact]
        public void HsrcTest()
        {
            // TODO unit test for the property 'Hsrc'
        }
    }
}
