/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = GsiApi.Client.OpenAPIDateConverter;

namespace GsiApi.Model
{
    /// <summary>
    /// SurveycalcXy2blPlGet200Response
    /// </summary>
    [DataContract(Name = "_surveycalc_xy2bl_pl_get_200_response")]
    public partial class SurveycalcXy2blPlGet200Response
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SurveycalcXy2blPlGet200Response" /> class.
        /// </summary>
        /// <param name="outputData">outputData.</param>
        public SurveycalcXy2blPlGet200Response(SurveycalcXy2blPlGet200ResponseOutputData outputData = default(SurveycalcXy2blPlGet200ResponseOutputData))
        {
            this.OutputData = outputData;
        }

        /// <summary>
        /// Gets or Sets OutputData
        /// </summary>
        [DataMember(Name = "OutputData", EmitDefaultValue = false)]
        public SurveycalcXy2blPlGet200ResponseOutputData OutputData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SurveycalcXy2blPlGet200Response {\n");
            sb.Append("  OutputData: ").Append(OutputData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
