/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = GsiApi.Client.OpenAPIDateConverter;

namespace GsiApi.Model
{
    /// <summary>
    /// SurveycalcXy2blPlGet200ResponseOutputData
    /// </summary>
    [DataContract(Name = "_surveycalc_xy2bl_pl_get_200_response_OutputData")]
    public partial class SurveycalcXy2blPlGet200ResponseOutputData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SurveycalcXy2blPlGet200ResponseOutputData" /> class.
        /// </summary>
        /// <param name="latitude">latitude.</param>
        /// <param name="longitude">longitude.</param>
        /// <param name="gridConv">gridConv.</param>
        /// <param name="scaleFactor">scaleFactor.</param>
        public SurveycalcXy2blPlGet200ResponseOutputData(double latitude = default(double), double longitude = default(double), decimal gridConv = default(decimal), decimal scaleFactor = default(decimal))
        {
            this.Latitude = latitude;
            this.Longitude = longitude;
            this.GridConv = gridConv;
            this.ScaleFactor = scaleFactor;
        }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [DataMember(Name = "latitude", EmitDefaultValue = false)]
        public double Latitude { get; set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [DataMember(Name = "longitude", EmitDefaultValue = false)]
        public double Longitude { get; set; }

        /// <summary>
        /// Gets or Sets GridConv
        /// </summary>
        [DataMember(Name = "gridConv", EmitDefaultValue = false)]
        public decimal GridConv { get; set; }

        /// <summary>
        /// Gets or Sets ScaleFactor
        /// </summary>
        [DataMember(Name = "scaleFactor", EmitDefaultValue = false)]
        public decimal ScaleFactor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SurveycalcXy2blPlGet200ResponseOutputData {\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  GridConv: ").Append(GridConv).Append("\n");
            sb.Append("  ScaleFactor: ").Append(ScaleFactor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
