/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = GsiApi.Client.OpenAPIDateConverter;

namespace GsiApi.Model
{
    /// <summary>
    /// GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData
    /// </summary>
    [DataContract(Name = "_geoid_calcgh_cgi_geoidcalc_pl_get_200_response_OutputData")]
    public partial class GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData" /> class.
        /// </summary>
        /// <param name="latitude">latitude.</param>
        /// <param name="longitude">longitude.</param>
        /// <param name="geoidHeight">geoidHeight.</param>
        public GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData(double latitude = default(double), double longitude = default(double), float geoidHeight = default(float))
        {
            this.Latitude = latitude;
            this.Longitude = longitude;
            this.GeoidHeight = geoidHeight;
        }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [DataMember(Name = "latitude", EmitDefaultValue = false)]
        public double Latitude { get; set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [DataMember(Name = "longitude", EmitDefaultValue = false)]
        public double Longitude { get; set; }

        /// <summary>
        /// Gets or Sets GeoidHeight
        /// </summary>
        [DataMember(Name = "geoidHeight", EmitDefaultValue = false)]
        public float GeoidHeight { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData {\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  GeoidHeight: ").Append(GeoidHeight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
