/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = GsiApi.Client.OpenAPIDateConverter;

namespace GsiApi.Model
{
    /// <summary>
    /// SurveycalcBl2stCalcPlGet200ResponseOutputData
    /// </summary>
    [DataContract(Name = "_surveycalc_bl2st_calc_pl_get_200_response_OutputData")]
    public partial class SurveycalcBl2stCalcPlGet200ResponseOutputData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SurveycalcBl2stCalcPlGet200ResponseOutputData" /> class.
        /// </summary>
        /// <param name="geoLength">geoLength.</param>
        /// <param name="azimuth1">azimuth1.</param>
        /// <param name="azimuth2">azimuth2.</param>
        public SurveycalcBl2stCalcPlGet200ResponseOutputData(double geoLength = default(double), double azimuth1 = default(double), double azimuth2 = default(double))
        {
            this.GeoLength = geoLength;
            this.Azimuth1 = azimuth1;
            this.Azimuth2 = azimuth2;
        }

        /// <summary>
        /// Gets or Sets GeoLength
        /// </summary>
        [DataMember(Name = "geoLength", EmitDefaultValue = false)]
        public double GeoLength { get; set; }

        /// <summary>
        /// Gets or Sets Azimuth1
        /// </summary>
        [DataMember(Name = "azimuth1", EmitDefaultValue = false)]
        public double Azimuth1 { get; set; }

        /// <summary>
        /// Gets or Sets Azimuth2
        /// </summary>
        [DataMember(Name = "azimuth2", EmitDefaultValue = false)]
        public double Azimuth2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SurveycalcBl2stCalcPlGet200ResponseOutputData {\n");
            sb.Append("  GeoLength: ").Append(GeoLength).Append("\n");
            sb.Append("  Azimuth1: ").Append(Azimuth1).Append("\n");
            sb.Append("  Azimuth2: ").Append(Azimuth2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
