/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GsiApi.Model;
using GsiApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GsiApi.Test.Model
{
    /// <summary>
    ///  Class for testing GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData
        //private GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData instance;

        public GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputDataTests()
        {
            // TODO uncomment below to create an instance of GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData
            //instance = new GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData
        /// </summary>
        [Fact]
        public void GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData
            //Assert.IsType<GeoidCalcghCgiGeoidcalcPlGet200ResponseOutputData>(instance);
        }

        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }

        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

        /// <summary>
        /// Test the property 'GeoidHeight'
        /// </summary>
        [Fact]
        public void GeoidHeightTest()
        {
            // TODO unit test for the property 'GeoidHeight'
        }
    }
}
