/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GsiApi.Model;
using GsiApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GsiApi.Test.Model
{
    /// <summary>
    ///  Class for testing GsigraCalcApiGravityCalculationGet200ResponseCalcResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GsigraCalcApiGravityCalculationGet200ResponseCalcResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GsigraCalcApiGravityCalculationGet200ResponseCalcResult
        //private GsigraCalcApiGravityCalculationGet200ResponseCalcResult instance;

        public GsigraCalcApiGravityCalculationGet200ResponseCalcResultTests()
        {
            // TODO uncomment below to create an instance of GsigraCalcApiGravityCalculationGet200ResponseCalcResult
            //instance = new GsigraCalcApiGravityCalculationGet200ResponseCalcResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GsigraCalcApiGravityCalculationGet200ResponseCalcResult
        /// </summary>
        [Fact]
        public void GsigraCalcApiGravityCalculationGet200ResponseCalcResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" GsigraCalcApiGravityCalculationGet200ResponseCalcResult
            //Assert.IsType<GsigraCalcApiGravityCalculationGet200ResponseCalcResult>(instance);
        }

        /// <summary>
        /// Test the property 'DataVer'
        /// </summary>
        [Fact]
        public void DataVerTest()
        {
            // TODO unit test for the property 'DataVer'
        }

        /// <summary>
        /// Test the property 'Gravity'
        /// </summary>
        [Fact]
        public void GravityTest()
        {
            // TODO unit test for the property 'Gravity'
        }

        /// <summary>
        /// Test the property 'GravityData'
        /// </summary>
        [Fact]
        public void GravityDataTest()
        {
            // TODO unit test for the property 'GravityData'
        }

        /// <summary>
        /// Test the property 'H'
        /// </summary>
        [Fact]
        public void HTest()
        {
            // TODO unit test for the property 'H'
        }

        /// <summary>
        /// Test the property 'LatDeg'
        /// </summary>
        [Fact]
        public void LatDegTest()
        {
            // TODO unit test for the property 'LatDeg'
        }

        /// <summary>
        /// Test the property 'LatDms'
        /// </summary>
        [Fact]
        public void LatDmsTest()
        {
            // TODO unit test for the property 'LatDms'
        }

        /// <summary>
        /// Test the property 'LonDeg'
        /// </summary>
        [Fact]
        public void LonDegTest()
        {
            // TODO unit test for the property 'LonDeg'
        }

        /// <summary>
        /// Test the property 'LonDms'
        /// </summary>
        [Fact]
        public void LonDmsTest()
        {
            // TODO unit test for the property 'LonDms'
        }

        /// <summary>
        /// Test the property 'Program'
        /// </summary>
        [Fact]
        public void ProgramTest()
        {
            // TODO unit test for the property 'Program'
        }

        /// <summary>
        /// Test the property 'DH'
        /// </summary>
        [Fact]
        public void DHTest()
        {
            // TODO unit test for the property 'DH'
        }
    }
}
