/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GsiApi.Model;
using GsiApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GsiApi.Test.Model
{
    /// <summary>
    ///  Class for testing GsigraCalcApiGravityCalculationGet200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GsigraCalcApiGravityCalculationGet200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GsigraCalcApiGravityCalculationGet200Response
        //private GsigraCalcApiGravityCalculationGet200Response instance;

        public GsigraCalcApiGravityCalculationGet200ResponseTests()
        {
            // TODO uncomment below to create an instance of GsigraCalcApiGravityCalculationGet200Response
            //instance = new GsigraCalcApiGravityCalculationGet200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GsigraCalcApiGravityCalculationGet200Response
        /// </summary>
        [Fact]
        public void GsigraCalcApiGravityCalculationGet200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GsigraCalcApiGravityCalculationGet200Response
            //Assert.IsType<GsigraCalcApiGravityCalculationGet200Response>(instance);
        }

        /// <summary>
        /// Test the property 'CalcResult'
        /// </summary>
        [Fact]
        public void CalcResultTest()
        {
            // TODO unit test for the property 'CalcResult'
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
    }
}
