/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GsiApi.Model;
using GsiApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GsiApi.Test.Model
{
    /// <summary>
    ///  Class for testing GsigraCalcApiGravityCalculationGet200ResponseCalcResultLatDms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GsigraCalcApiGravityCalculationGet200ResponseCalcResultLatDmsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GsigraCalcApiGravityCalculationGet200ResponseCalcResultLatDms
        //private GsigraCalcApiGravityCalculationGet200ResponseCalcResultLatDms instance;

        public GsigraCalcApiGravityCalculationGet200ResponseCalcResultLatDmsTests()
        {
            // TODO uncomment below to create an instance of GsigraCalcApiGravityCalculationGet200ResponseCalcResultLatDms
            //instance = new GsigraCalcApiGravityCalculationGet200ResponseCalcResultLatDms();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GsigraCalcApiGravityCalculationGet200ResponseCalcResultLatDms
        /// </summary>
        [Fact]
        public void GsigraCalcApiGravityCalculationGet200ResponseCalcResultLatDmsInstanceTest()
        {
            // TODO uncomment below to test "IsType" GsigraCalcApiGravityCalculationGet200ResponseCalcResultLatDms
            //Assert.IsType<GsigraCalcApiGravityCalculationGet200ResponseCalcResultLatDms>(instance);
        }

        /// <summary>
        /// Test the property 'Deg'
        /// </summary>
        [Fact]
        public void DegTest()
        {
            // TODO unit test for the property 'Deg'
        }

        /// <summary>
        /// Test the property 'Min'
        /// </summary>
        [Fact]
        public void MinTest()
        {
            // TODO unit test for the property 'Min'
        }

        /// <summary>
        /// Test the property 'Sec'
        /// </summary>
        [Fact]
        public void SecTest()
        {
            // TODO unit test for the property 'Sec'
        }
    }
}
