/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GsiApi.Model;
using GsiApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GsiApi.Test.Model
{
    /// <summary>
    ///  Class for testing SurveycalcXy2stPlGet200ResponseOutputData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SurveycalcXy2stPlGet200ResponseOutputDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SurveycalcXy2stPlGet200ResponseOutputData
        //private SurveycalcXy2stPlGet200ResponseOutputData instance;

        public SurveycalcXy2stPlGet200ResponseOutputDataTests()
        {
            // TODO uncomment below to create an instance of SurveycalcXy2stPlGet200ResponseOutputData
            //instance = new SurveycalcXy2stPlGet200ResponseOutputData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SurveycalcXy2stPlGet200ResponseOutputData
        /// </summary>
        [Fact]
        public void SurveycalcXy2stPlGet200ResponseOutputDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SurveycalcXy2stPlGet200ResponseOutputData
            //Assert.IsType<SurveycalcXy2stPlGet200ResponseOutputData>(instance);
        }

        /// <summary>
        /// Test the property 'GeoLength'
        /// </summary>
        [Fact]
        public void GeoLengthTest()
        {
            // TODO unit test for the property 'GeoLength'
        }

        /// <summary>
        /// Test the property 'GridBearing1'
        /// </summary>
        [Fact]
        public void GridBearing1Test()
        {
            // TODO unit test for the property 'GridBearing1'
        }

        /// <summary>
        /// Test the property 'GridBearing2'
        /// </summary>
        [Fact]
        public void GridBearing2Test()
        {
            // TODO unit test for the property 'GridBearing2'
        }
    }
}
