/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GsiApi.Model;
using GsiApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GsiApi.Test.Model
{
    /// <summary>
    ///  Class for testing SurveycalcBl2xyPlGet200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SurveycalcBl2xyPlGet200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SurveycalcBl2xyPlGet200Response
        //private SurveycalcBl2xyPlGet200Response instance;

        public SurveycalcBl2xyPlGet200ResponseTests()
        {
            // TODO uncomment below to create an instance of SurveycalcBl2xyPlGet200Response
            //instance = new SurveycalcBl2xyPlGet200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SurveycalcBl2xyPlGet200Response
        /// </summary>
        [Fact]
        public void SurveycalcBl2xyPlGet200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SurveycalcBl2xyPlGet200Response
            //Assert.IsType<SurveycalcBl2xyPlGet200Response>(instance);
        }

        /// <summary>
        /// Test the property 'OutputData'
        /// </summary>
        [Fact]
        public void OutputDataTest()
        {
            // TODO unit test for the property 'OutputData'
        }
    }
}
