/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GsiApi.Model;
using GsiApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GsiApi.Test.Model
{
    /// <summary>
    ///  Class for testing SurveycalcTransPlGet200ResponseOutputData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SurveycalcTransPlGet200ResponseOutputDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SurveycalcTransPlGet200ResponseOutputData
        //private SurveycalcTransPlGet200ResponseOutputData instance;

        public SurveycalcTransPlGet200ResponseOutputDataTests()
        {
            // TODO uncomment below to create an instance of SurveycalcTransPlGet200ResponseOutputData
            //instance = new SurveycalcTransPlGet200ResponseOutputData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SurveycalcTransPlGet200ResponseOutputData
        /// </summary>
        [Fact]
        public void SurveycalcTransPlGet200ResponseOutputDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SurveycalcTransPlGet200ResponseOutputData
            //Assert.IsType<SurveycalcTransPlGet200ResponseOutputData>(instance);
        }

        /// <summary>
        /// Test the property 'GeocentricX'
        /// </summary>
        [Fact]
        public void GeocentricXTest()
        {
            // TODO unit test for the property 'GeocentricX'
        }

        /// <summary>
        /// Test the property 'GeocentricY'
        /// </summary>
        [Fact]
        public void GeocentricYTest()
        {
            // TODO unit test for the property 'GeocentricY'
        }

        /// <summary>
        /// Test the property 'GeocentricZ'
        /// </summary>
        [Fact]
        public void GeocentricZTest()
        {
            // TODO unit test for the property 'GeocentricZ'
        }
    }
}
