/*
 * 国土地理院測量計算API
 *
 * 国土地理院が提供する測量計算のためのREST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GsiApi.Model;
using GsiApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GsiApi.Test.Model
{
    /// <summary>
    ///  Class for testing SurveycalcBl2xyPlGet200ResponseOutputData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SurveycalcBl2xyPlGet200ResponseOutputDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SurveycalcBl2xyPlGet200ResponseOutputData
        //private SurveycalcBl2xyPlGet200ResponseOutputData instance;

        public SurveycalcBl2xyPlGet200ResponseOutputDataTests()
        {
            // TODO uncomment below to create an instance of SurveycalcBl2xyPlGet200ResponseOutputData
            //instance = new SurveycalcBl2xyPlGet200ResponseOutputData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SurveycalcBl2xyPlGet200ResponseOutputData
        /// </summary>
        [Fact]
        public void SurveycalcBl2xyPlGet200ResponseOutputDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SurveycalcBl2xyPlGet200ResponseOutputData
            //Assert.IsType<SurveycalcBl2xyPlGet200ResponseOutputData>(instance);
        }

        /// <summary>
        /// Test the property 'PublicX'
        /// </summary>
        [Fact]
        public void PublicXTest()
        {
            // TODO unit test for the property 'PublicX'
        }

        /// <summary>
        /// Test the property 'PublicY'
        /// </summary>
        [Fact]
        public void PublicYTest()
        {
            // TODO unit test for the property 'PublicY'
        }

        /// <summary>
        /// Test the property 'GridConv'
        /// </summary>
        [Fact]
        public void GridConvTest()
        {
            // TODO unit test for the property 'GridConv'
        }

        /// <summary>
        /// Test the property 'ScaleFactor'
        /// </summary>
        [Fact]
        public void ScaleFactorTest()
        {
            // TODO unit test for the property 'ScaleFactor'
        }
    }
}
